[package]
name = "CocoaDrawRust"
version = "0.1.0"
edition = "2021"

[dependencies]
objc2 = "0.5.2"
objc2-foundation = { version = "0.2.2", features = ["all"] }

[target.'cfg(target_os = "macos")'.dependencies]
objc2-app-kit = { version = "0.2.2", features = ["all"] }
